### ISSUE TITLE
Posts should have visibility settings

### ISSUE THREAD

**Issue by jordanbyron** [mendicant-original/community#11]
- Mendicant vs Public

**Comment by samnang** [comment]
Should find a good way to know if a user is a mendicant user? What do you think if we mark the user status to be mendicant when creating the user instead of checking university-web every time browsing posts. But it has one problem if the user sign up and use community, and then later s/he becomes mendicant student, so the status doesn't update. We could solve this issue to update user status every time user sign in.

What do you think?

**Comment by ptn** [comment]
> But it has one problem if the user sign up and use community, and then later s/he becomes mendicant student

I'm not sure if this wasn't always this way, but currently one can't actually sign up to use Community, you have to be alumni for that.

Then the login status is enough to know what type of post to show: if the user is logged in, show him everything, if he's not, show him only the public ones.

**Comment by practicingruby** [comment]
@samnang: What @ptn said is correct. Currently and for the foreseeable future every logged in member can be assumed as a MU member.

**Comment by samnang** [comment]
That's a lot of easier. So just add a boolean field into article table and show a toggle button in form. I could start working on it.

**Comment by jordanbyron** [comment]
@samnang let's wrap up your other patch first. Then once that's all set and no one else has claimed this one you can start working on it :wink2:

**Comment by samnang** [comment]
@jordanbyron yep :smiley:

**Comment by wicz** [comment]
@jordanbyron @sandal Feel free to assign it to me :smile:

Anyone could make a post public or only admins?

**Comment by practicingruby** [comment]
@wicz: assigned. Anyone can make a post public, and it should be public by default (I think)
