### ISSUE TITLE
sticky updates

### ISSUE THREAD

**Issue by practicingruby** [mendicant-original/community#27]

**Comment by wicz** [comment]
Hi @sandal and @jordanbyron, what are your plans for this feature? I think of:
- Admin can mark/unmark articles as sticky
- Sticky articles appears at the top of the list
- Sticky appears at the top even if there are newer articles
- Sticky appears at the top even if user isn't on the first page
- Sticky have something that identify they as sticky, e.g. a pin icon

What else?

**Comment by practicingruby** [comment]
@wicz / @jordanbyron: I think all of those ideas sound correct, though we probably don't need the "appear at the top even if user isn't on the first page" feature.

**Comment by wicz** [comment]
Great! Feel free to assign it to me.

I'll drop 4) for now. No worries if you change your mind later.

**Comment by ptn** [comment]
What kind of posts would be marked as sticky? Something like announcements from staff?

**Comment by practicingruby** [comment]
@ptn: Pretty much anything time sensitive (upcoming events) or extremely important (upcoming changes to infrastructures, or major announcements) . But with the slowness of the site currently, it'll likely be used rarely.

**Comment by wicz** [comment]
Hello, I've pushed some code for this feature to my branch.  One thing though, the access control to mark an update as sticky is way naive. For now it has a simple conditional in the form to show the sticky checkbox if `current_user.admin?`. Anyone could easily inject `article[sticky]` into the form (or the request) and make it sticky.

By the end of the week I'll have a proper way to allow only admins to do that.

**Comment by jordanbyron** [comment]
@wicz I'm not terribly concerned about our community members injecting code to make their posts sticky, but you are correct this is a potential security problem.

In the past I've added `attr_proteced` to those attributes and did a manual `update_attribute` call in the controller if the user had the correct rights. I know there has to be a better way, and I am sure someone has written a gem to handle these types of problems.

Maybe you could do a little research and share what you find back here. I'll do the same. Oh and if you've got code working feel free to send over a pull request so I can get you some feedback :bowtie:

Thanks for working on this!

**Comment by wicz** [comment]
Well, after a little research here goes our options:

##### Use rails 3.1 built-in [MassAssignSecurity](http://api.rubyonrails.org/classes/ActiveModel/MassAssignmentSecurity/ClassMethods.html)

I still have mixed feelings about it. It's nice because we don't add external dependencies and since it's a module, we can choose to implement the access control in the controller or model or whatever. And using `attr_accessible` is also interesting cause it enforces you to use the whitelist mass assign pattern (ideas towards this approach already in [3.2](https://github.com/rails/rails/issues/3453)). But, it's limited because it is static. All it does is check if the value of `as` passed on the assignment has the same value at the definition. Due this we have to explicitly write all the rules, which is not very DRY:

``` ruby
attr_accessible :title, :body
attr_accessible :title, :body, :sticky, as: 'admin'
```

We could use the blacklist pattern instead. The same un-DRY-ness appears if we have more than one non-admin role:

``` ruby
attr_protected :sticky, as: 'user'
attr_protected :sticky, as: 'guest'
```

Life would be easier if we could have conditionals like `attr_accessible :sticky, if: admin?`

##### [param_protected](https://github.com/cjbottaro/param_protected) gem

This gem is like `attr_accessible` and `attr_protected` on steroids, but for controllers only. Looks like with this we can easily have the conditional I commented before:

``` ruby
param_accessible :sticky, if: current_user.admin?
```

##### Our own super (simple) effective solution

We could just mangle the params ourselves:

``` ruby
params[:article].delete(:sticky) unless current_user.admin?
```

Thoughts?

**Comment by practicingruby** [comment]
@wicz: Let's not bother with this. I have absolutely no fear of abuse on this, particularly because all update functionality is behind an authentication wall. If we have an alumnus go rogue, we have a lot more to worry about than them making some sticky announcements!

**Comment by practicingruby** [comment]
@wicz: To clarify, we have no plans in the near future to expose the editable portions of the site to non-MU community members, so I'm not sure why this is even being discussed.

**Comment by wicz** [comment]
Ok then, I'll just hide the sticky option for non-admins.

**Comment by practicingruby** [comment]
@wicz Thanks. Your research won't go to waste, there are definitely situations where we're going to need to know this and we haven't done the legwork in the past to figure it out. For right now, we're just being aggressively minimal with this app :)
