### ISSUE TITLE
Feature idea: share posts on twitter / facebook / google+

### ISSUE THREAD

**Issue by jaimeiniesta** [mendicant-original/community#40]
Adding buttons for sharing a post on Twitter / Facebook / Google+ should give more visibility.

What do you think? I can work on this.

**Comment by jordanbyron** [comment]
@jaimeiniesta not sure if you saw, but we do [tweet updates](http://twitter.com/mendicant_news/status/164682977534689280) via [mendicant_news](http://twitter.com/mendicant_news) on twitter. 

@sandal and I are trying really, really hard to make sure we kill any and all new features that come up until they _keep_ coming up and we just can't ignore them anymore. We can to keep community lean and mean and avoid the feature rot we experienced in university-web.

If someone really wants to share a link to community, they can easily write up their own tweet or facebook / google+ update. If you're still interested in contributing to community, feel free to signup for the [community week of Mending Mendicant](http://community.mendicantuniversity.org/activities/mending-mendicant-community-week) :smile:

**Comment by jaimeiniesta** [comment]
You're right, I've found that including social buttons to make it easier/faster to twitt works great, but I also think this could lead to feature rot.

**Comment by practicingruby** [comment]
I find that autotweet things generate really low signal shares. I much rather someone take the time to write up something in their own words.

Also, I think "share" buttons look a bit hungry... especially when it comes to this site I don't think it's needed because we're looking primarily to reach the fellow members of our existing community, not necessarily broadcast to the world at large.

That said, I certainly encourage posting links to updates by hand to various social networks, but the primary goal of this site isn't wide-scale promotions.
